name: Deploy to ShinyApps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install rsconnect
        run: Rscript -e "install.packages('rsconnect')"

      - name: Deploy to ShinyApps.io
        env:
          SHINYAPPS_USERNAME: ${{ secrets.SHINYAPPS_USERNAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e "rsconnect::setAccountInfo(
              name=Sys.getenv('SHINYAPPS_USERNAME'),
              token=Sys.getenv('SHINYAPPS_TOKEN'),
              secret=Sys.getenv('SHINYAPPS_SECRET')
          )"
          Rscript -e "rsconnect::deployApp(appDir='.')"
